### ISSUE TITLE
Nintendo

### ISSUE THREAD

**Issue by marceloverass** [VictorBren0/playgame-page#1]
Se me permite te ajudar, você tem que fazer uma correção bem simples no HTML, o nome da empresa é NI"N"TENDO, apesar da nossa pronúncia acabar saindo nitendo mesmo.

Mas de resto tá tudo certo mano, seu site tá bem bonito e fluído, parabéns!

**Comment by VictorBren0** [comment]
Olá, realmente está errado, vou fazer a correção, obrigado por avisar. 😁

**Comment by marceloverass** [comment]
Tamo junto!!
